---
# handlers file for haproxy
- name: start haproxy
  systemd:
    daemon_reload: yes
    name: haproxy
    state: started

- name: stop haproxy
  systemd:
    daemon_reload: yes
    name: haproxy
    state: stopped

- name: restart haproxy
  systemd:
    daemon_reload: yes
    name: haproxy
    state: restarted

- name: restart rsyslog
  systemd:
    daemon_reload: yes
    name: rsyslog
    state: restarted
